// Generated by Livo — wallet-connect shell. Deploy a contract, then run
// scaffold_frontend to wire typed hooks + a contract demo into this page.
import { ConnectWallet } from "./livo";
import { useEffect, useState } from "react";

function ApiStatus() {
  const [state, setState] = useState("checking");
  useEffect(() => {
    fetch("/api/health")
      .then((r) => r.json())
      .then((d) => setState(d && d.ok ? "ok" : "error"))
      .catch(() => setState("error"));
  }, []);
  const label = state === "checking" ? "checking…" : state === "ok" ? "✓ connected" : "✗ not reachable";
  return (
    <p>Backend API (<code>/api</code>): <strong>{label}</strong> — edit <code>api/index.js</code>, then <code>deploy_api</code>.</p>
  );
}

export default function App() {
  return (
    <main style={{ maxWidth: 720, margin: "2rem auto", fontFamily: "system-ui", padding: "0 1rem" }}>
      <h1>sol-defi-super-app</h1>
      <p>Your Livo site is live and wallet-connected. Connect below, then deploy a contract and run scaffold_frontend to add typed contract hooks.</p>
      <ApiStatus />
      <div style={{ display: "flex", gap: 12, flexWrap: "wrap", marginTop: 16 }}>
        <ConnectWallet />
      </div>
    </main>
  );
}
