// Generated by Livo — normalized auth hook. SAME shape across wagmi/Privy/Dynamic,
// so app code never changes when you switch the login provider (scaffold_frontend
// auth=…). For the login UI use <ConnectWallet/>; useAuth gives the state + an
// imperative login()/logout() for custom UIs.
import { useConnection, useConnect, useDisconnect } from "wagmi";

export interface AuthState {
  /** Connected wallet address (undefined when signed out). */
  address?: `0x${string}`;
  /** A wallet is connected. */
  isConnected: boolean;
  /** Logged in. For wallet-only (wagmi) this equals isConnected; for Privy/Dynamic
   *  it reflects their session (which can exist before a wallet is attached). */
  isAuthenticated: boolean;
  /** Identity email, when the login method supplies one (Privy / Dynamic social). */
  email?: string;
  /** Start the login flow. For the full UI render <ConnectWallet/>; this is for
   *  custom buttons. */
  login: () => void;
  logout: () => void;
}

export function useAuth(): AuthState {
  const { address, isConnected } = useConnection();
  const { connect, connectors } = useConnect();
  const { disconnect } = useDisconnect();
  return {
    address,
    isConnected: Boolean(isConnected),
    isAuthenticated: Boolean(isConnected), // wallet-only: connected === authenticated
    email: undefined,
    // For the full modal, render <ConnectWallet/>; this connects the first connector.
    login: () => { const c = connectors[0]; if (c) connect({ connector: c }); },
    logout: () => disconnect(),
  };
}
