// Generated by Livo — wallet connect from @livo-build/kit.
// It is NEUTRAL by default — style it to match your app (override CSS vars like
// --wm-accent, or pass a classNames prop), or build your own on
// { WalletModal, useWalletConnectors } from "@livo-build/kit". See the kit's STYLING.md.
export { ConnectWallet } from "@livo-build/kit";
