// Generated by Livo.
import { useWaitForTransactionReceipt } from "wagmi";

export function TxStatus({ hash }: { hash?: `0x${string}` }) {
  const { isLoading, isSuccess, isError } = useWaitForTransactionReceipt({ hash });
  if (!hash) return null;
  const state = isLoading ? "pending…" : isSuccess ? "confirmed ✓" : isError ? "failed ✗" : "";
  return (
    <div style={{ fontFamily: "monospace", fontSize: 12 }}>
      tx {hash.slice(0, 10)}… {state}
    </div>
  );
}
