// Generated by Livo — wagmi connectors.
import { http, createConfig } from "wagmi";
import { sepolia } from "wagmi/chains";
import { injected, coinbaseWallet } from "wagmi/connectors";

// injected() discovers MetaMask/Rabby/Frame via EIP-6963; WalletConnect is opt-in (re-run with walletconnect:true).
export const wagmiConfig = createConfig({
  chains: [sepolia],
  connectors: [
    injected(),
    coinbaseWallet({ appName: "sol-defi-super-app" }),
  ],
  transports: {
    [sepolia.id]: http(),
  },
});
