// Generated by Livo — wrap your app in <Web3Provider>. Providers come from
// @livo-build/kit (LivoWeb3Provider = wagmi + react-query); your wagmi config
// (chains/connectors) stays here in ./wagmi so it's easy to edit.
import type { ReactNode } from "react";
import { LivoWeb3Provider } from "@livo-build/kit";
import { wagmiConfig } from "./wagmi";

export function Web3Provider({ children }: { children: ReactNode }) {
  return <LivoWeb3Provider config={wagmiConfig}>{children}</LivoWeb3Provider>;
}
